services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    volumes:
      - ./data:/data
    ports:
      - 127.0.0.1:8025:8025
      - 1025:1025
    env_file:
      - .env
    restart: unless-stopped
